# Form implementation generated from reading ui file '.\tela_inicial.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from util.password import PasswordEdit


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(192, 180)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalWidget.setGeometry(QtCore.QRect(9, 9, 175, 163))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalWidget)
        self.label.setStyleSheet("font-size:15pt;\n"
"                                color: rgb(0, 0, 0);\n"
"                            ")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.login = QtWidgets.QLineEdit(parent=self.verticalWidget)
        self.login.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"                                color: rgb(0, 0, 0);\n"
"                            ")
        self.login.setObjectName("login")
        self.verticalLayout.addWidget(self.login)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalWidget)
        self.label_2.setStyleSheet("font-size:15pt;\n"
"                                color: rgb(0, 0, 0);\n"
"                            ")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.senha = PasswordEdit(parent=self.verticalWidget)
        self.senha.setStyleSheet("color: rgb(0, 0, 0);")
        self.senha.setObjectName("senha")
        self.verticalLayout.addWidget(self.senha)
        self.btn_login = QtWidgets.QPushButton(parent=self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_login.sizePolicy().hasHeightForWidth())
        self.btn_login.setSizePolicy(sizePolicy)
        self.btn_login.setMinimumSize(QtCore.QSize(157, 24))
        self.btn_login.setStyleSheet("background-color:rgb(0, 62, 122);\n"
"                                color: rgb(255, 255, 255);\n"
"                                font-size:15pt;\n"
"                            ")
        self.btn_login.setDefault(True)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout.addWidget(self.btn_login, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout.setStretch(4, 255)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Login"))
        self.label_2.setText(_translate("Dialog", "Senha"))
        self.btn_login.setText(_translate("Dialog", "Entrar no maua.net"))
