# Form implementation generated from reading ui file '.\tela_inicial.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(193, 181)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 175, 163))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setStyleSheet("font-size:15pt;\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.login = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.login.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.login.setObjectName("login")
        self.verticalLayout.addWidget(self.login)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setStyleSheet("font-size:15pt;\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.senha = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.senha.setStyleSheet("color: rgb(0, 0, 0);")
        self.senha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.senha.setObjectName("senha")
        self.verticalLayout.addWidget(self.senha)
        self.btn_login = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_login.setStyleSheet("background-color:rgb(0, 62, 122);\n"
"color: rgb(255, 255, 255);\n"
"font-size:15pt;")
        self.btn_login.setDefault(True)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout.addWidget(self.btn_login, 0, QtCore.Qt.AlignmentFlag.AlignLeft)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Login"))
        self.label_2.setText(_translate("Dialog", "Senha"))
        self.btn_login.setText(_translate("Dialog", "Entrar no maua.net"))
